name: Publish wiki
on:
  push:
    branches: 
      - 2024.6.*
      - 2024.1.0-prerelease
    paths:
      - wiki/**
      - .github/workflows/wiki.yaml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Andrew-Chen-Wang/github-wiki-action@v4.4.0
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: '$GITHUB_WORKSPACE/components/ehmtxv2'
          doxyfile-path: "$GITHUB_WORKSPACE"
